#! /bin/bash
#
#   - Discover the Cloudformation stack that booted the current instance via instance meta-data.
#   -


pkg="setup-cloudformation-environment"
version="1.0"
environment_file_path="/etc/cloudformation-environment"

export AWS_DEFAULT_REGION="$(curl -sSL http://169.254.169.254/latest/dynamic/instance-identity/document | jq --raw-output .region)"
if [[ ! $AWS_DEFAULT_REGION ]]; then
    echo "$pkg: failed to get region"
    exit 1
fi

ec2_instance_id="$(curl -sSL http://169.254.169.254/latest/meta-data/instance-id)"
if [[ ! $ec2_instance_id ]]; then
    echo "$pkg: failed to get instance id from instance metadata"
    exit 2
fi

exit 0


# .Tags | map(select(.Key | startswith("aws:cloudformation:"))) | map({key: .Key, value: .Value}) | from_entries
